apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdbdata
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.220.4.49
    path: "/couchdbdata"
